config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  resources :ghosts, only: [:index, :new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ghost.rb
class Ghost < ApplicationRecord
  validates :person, presence: true, length: { maximum: 100, minimum: 3 }
  validates :eulogy, presence: true, length: { maximum: 600, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ghosts_controller.rb
class GhostsController < ApplicationController

  def index
    @ghosts = Ghost.all
  end

  def new
    @ghost = Ghost.new
  end

  def create
    @ghost = Ghost.create(ghost_params)
    if @ghost.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @ghost = Ghost.find_by_id(params[:id])
    if @ghost.blank?
      render plain: 'Not Found', status: :not_found
    end
  end

  private

  def ghost_params
    params.require(:ghost).permit(:person, :eulogy)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ghosts_helper.rb
module GhostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ghosts/index.html.erb
<div class="row">
  <% @ghosts.each do |ghost| %>
    <div class="container col-6 col-sm-3 text-center">
      <%= image_tag("#{rand(1..10)}.png") %>
          <div class="top-centered"><%= ghost.person %></div>
          <div class="centered"><%= ghost.eulogy %></div>
    </div>
  <% end %>
</div>

app/views/ghosts/new.html.erb
<div class="col-8 offset-2">
<h1>Who will be missed?</h1>

<%= simple_form_for @ghost do |f| %>
  <%= f.input :person %>
  <span>Pets are people too.</span>
  <br /><br />
  <%= f.input :eulogy %>
  <%= f.submit "May this soul rest in peace." %>
<% end %>
</div>

app/views/ghosts/show.html.erb
<%= @ghost.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cemented In Code</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-fixed-bottom" id="navMenu">
  <div class="container">
    <div class="row">
          <div class="col-4">
            <%= link_to image_tag("seek.png"), ghosts_path %>
          </div>
          <div class="col-4 text-center">
            <%= link_to image_tag("cement.png"), root_path %>
          </div>
          <div class="col-4 text-right">
            <%= link_to image_tag("new.png"), new_ghost_path  %>
          </div>
    </div>
  </div>
</nav>

      

    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="welcome col-10 offset-1 text-center">
  <%= link_to image_tag("open.png"), ghosts_path %>
</div>